from __future__ import annotations

import hashlib
import re
import time
from collections.abc import Callable
from pathlib import Path
from typing import Any

from .config import cfg_get, cfg_list, cfg_number


class SourceIngestFlow:
    """Source ingestion, chunking, and source-local evidence recommendation."""

    def __init__(
        self,
        backend: Any,
        *,
        id_factory: Callable[[str], str],
        ts_factory: Callable[[], str],
        text_hash: Callable[[str], str],
    ) -> None:
        self.backend = backend
        self._new_id = id_factory
        self._now_ts = ts_factory
        self._sha256_text = text_hash

    def safe_resolve_uri(self, uri: str) -> Path:
        path = Path(uri)
        if not path.is_absolute():
            path = self.backend.root / path
        resolved = path.resolve()
        try:
            resolved.relative_to(self.backend.root)
        except ValueError as exc:
            raise ValueError(f"Refusing to read outside DOCGRAPH_ROOT: {uri}") from exc
        return resolved

    def safe_read_uri(self, uri: str) -> str:
        resolved = self.safe_resolve_uri(uri)
        return resolved.read_text(encoding="utf-8", errors="replace")

    def existing_repo_file_for_uri(self, uri: str) -> Path | None:
        if re.match(r"^[A-Za-z][A-Za-z0-9+.-]*://", uri):
            return None
        path = Path(uri)
        if not path.is_absolute():
            path = self.backend.root / path
        resolved = path.resolve()
        try:
            resolved.relative_to(self.backend.root)
        except ValueError:
            return None
        return resolved if resolved.is_file() else None

    def text_size_bytes(self, text: str) -> int:
        return len(text.encode("utf-8", errors="replace"))

    def source_limit_bytes(self, config_key: str) -> int:
        limit = int(cfg_number(self.backend.config, f"source_handling.{config_key}", 0))
        return max(0, limit)

    def enforce_source_size_limit(self, *, uri: str, source_kind: str, size_bytes: int, config_key: str) -> None:
        limit = self.source_limit_bytes(config_key)
        if limit <= 0 or size_bytes <= limit:
            return
        self.backend._log(
            "warning",
            "ingest.rejected",
            reason="source_too_large",
            uri=uri,
            source_kind=source_kind,
            content_bytes=size_bytes,
            limit_bytes=limit,
        )
        raise ValueError(
            f"refusing to ingest {source_kind} source {uri!r}: "
            f"{size_bytes} bytes exceeds source_handling.{config_key}={limit}; "
            "ingest only focused evidence or raise the configured limit deliberately"
        )

    def source_id_for_uri(self, uri: str) -> str:
        return "src_" + hashlib.sha1(uri.encode("utf-8")).hexdigest()[:16]

    def chunk_content(self, content: str, source_type: str) -> list[tuple[str, str]]:
        lines = content.splitlines()
        line_source_types = set(cfg_list(self.backend.config, "source_handling.line_chunk_source_types"))
        if source_type in line_source_types or len(lines) > 40:
            chunks: list[tuple[str, str]] = []
            step = max(1, int(cfg_get(self.backend.config, "source_handling.lines_per_chunk", 60)))
            overlap = max(0, int(cfg_get(self.backend.config, "source_handling.line_chunk_overlap", 5)))
            i = 0
            while i < len(lines):
                j = min(len(lines), i + step)
                text = "\n".join(lines[i:j]).strip()
                if text:
                    chunks.append((f"lines {i + 1}-{j}", text))
                if j == len(lines):
                    break
                i = max(j - overlap, i + 1)
            return chunks
        paras = [p.strip() for p in re.split(r"\n\s*\n", content) if p.strip()]
        out: list[tuple[str, str]] = []
        buf: list[str] = []
        idx = 1
        for p in paras:
            if sum(len(x) for x in buf) + len(p) > int(cfg_get(self.backend.config, "source_handling.paragraph_max_chars", 1600)) and buf:
                out.append((f"paragraph group {idx}", "\n\n".join(buf)))
                idx += 1
                buf = []
            buf.append(p)
        if buf:
            out.append((f"paragraph group {idx}", "\n\n".join(buf)))
        if not out and content.strip():
            out.append(("content", content.strip()))
        return out

    def reject_generated_doc_source(self, uri: str, content: str | None = None) -> None:
        norm_uri = uri.replace("\\", "/")
        basename = Path(norm_uri).name.lower()
        rendered_markers = (
            "/docs/rendered/",
            "docs/rendered/",
            "/rendered/",
        )
        content_prefix = (content or "")[:2000].lower()
        generated_content = "generated by render_docs" in content_prefix or "generated by docgraph" in content_prefix
        rendered_path = any(marker in norm_uri for marker in rendered_markers)
        generated_architecture_md = basename == "architecture.md" and generated_content
        if rendered_path or generated_architecture_md:
            raise ValueError(
                "refusing to ingest generated DocGraph output as evidence; "
                "exclude docs/rendered/* and generated architecture.md, and ingest original source docs/logs/code instead"
            )

    def ingest_source(
        self,
        source_type: str,
        uri: str,
        content: str | None = None,
        episode_type: str = "snapshot",
        name: str | None = None,
        evidence_hint: str | None = None,
        claim_text: str | None = None,
        evidence_lines: list[dict[str, int]] | None = None,
        recommend_limit: int = 5,
    ) -> dict[str, Any]:
        started = time.perf_counter()
        has_inline_content = content is not None
        inline_content_bytes = self.text_size_bytes(content) if content is not None else None
        self.backend._log(
            "info",
            "ingest.start",
            source_type=source_type,
            uri=uri,
            episode_type=episode_type,
            has_inline_content=has_inline_content,
            inline_content_bytes=inline_content_bytes,
            name=name,
        )
        if content is None:
            resolved = self.safe_resolve_uri(uri)
            file_size_bytes = resolved.stat().st_size
            self.enforce_source_size_limit(
                uri=uri,
                source_kind="file-backed",
                size_bytes=file_size_bytes,
                config_key="max_file_ingest_bytes",
            )
            content = resolved.read_text(encoding="utf-8", errors="replace")
        else:
            if bool(cfg_get(self.backend.config, "source_handling.reject_inline_content_for_repo_files", True)):
                repo_file = self.existing_repo_file_for_uri(uri)
                if repo_file is not None:
                    self.backend._log(
                        "warning",
                        "ingest.rejected",
                        reason="inline_content_for_repo_file",
                        uri=uri,
                        repo_path=str(repo_file),
                        content_bytes=inline_content_bytes,
                    )
                    raise ValueError(
                        f"refusing inline content for repository-local source {uri!r}; "
                        "omit content and let dg_ingest_source read the repo-relative uri"
                    )
            self.enforce_source_size_limit(
                uri=uri,
                source_kind="inline",
                size_bytes=inline_content_bytes or 0,
                config_key="max_inline_content_bytes",
            )
        content_bytes = self.text_size_bytes(content)
        self.reject_generated_doc_source(uri, content)
        source_id = self.source_id_for_uri(uri)
        content_hash = self._sha256_text(content)
        ts = self._now_ts()
        cur = self.backend.conn.cursor()
        existing = cur.execute("SELECT * FROM sources WHERE uri=?", (uri,)).fetchone()
        if existing and existing["current_hash"] == content_hash:
            chunk_refs = self.chunk_refs_for_source(existing["source_id"])
            recommended = self.recommend_evidence_candidates(
                existing["source_id"],
                evidence_hint=evidence_hint,
                claim_text=claim_text,
                evidence_lines=evidence_lines,
                limit=recommend_limit,
            )
            result = {
                "status": "unchanged",
                "source_id": existing["source_id"],
                "current_hash": content_hash,
                "chunks": len(chunk_refs),
                "content_bytes": content_bytes,
                "chunk_ids": [c["chunk_id"] for c in chunk_refs],
                "chunk_refs": chunk_refs,
                "recommended_evidence_candidates": recommended,
                "recommendation_warning": self.evidence_recommendation_warning(recommended, evidence_hint, claim_text, evidence_lines),
                "evidence_note": "Use these exact chunk_ids for claim evidence; do not infer chunk IDs from source_id or episode_id.",
            }
            self.backend._log(
                "info",
                "ingest.unchanged",
                source_id=existing["source_id"],
                uri=uri,
                content_bytes=content_bytes,
                chunks=len(chunk_refs),
                elapsed_ms=(time.perf_counter() - started) * 1000,
            )
            return result

        old_chunk_ids = []
        supersedes_episode_id = None
        if existing:
            source_id = existing["source_id"]
            old_eps = cur.execute(
                "SELECT episode_id FROM episodes WHERE source_id=? AND status='active' ORDER BY created_at DESC",
                (source_id,),
            ).fetchall()
            if old_eps:
                supersedes_episode_id = old_eps[0]["episode_id"]
            old_chunk_ids = [
                r["chunk_id"]
                for r in cur.execute(
                    "SELECT chunk_id FROM chunks WHERE source_id=? AND status='active'", (source_id,)
                ).fetchall()
            ]
        with self.backend.conn:
            if existing:
                self.backend.conn.execute(
                    "UPDATE sources SET current_hash=?, status='active', updated_at=? WHERE source_id=?",
                    (content_hash, ts, source_id),
                )
                self.backend.conn.execute(
                    "UPDATE episodes SET status='superseded' WHERE source_id=? AND status='active'",
                    (source_id,),
                )
                self.backend.conn.execute(
                    "UPDATE chunks SET status='stale' WHERE source_id=? AND status='active'",
                    (source_id,),
                )
                if old_chunk_ids:
                    marks = ",".join("?" for _ in old_chunk_ids)
                    self.backend.conn.execute(
                        f"UPDATE claim_evidence SET status='stale' WHERE chunk_id IN ({marks})",
                        old_chunk_ids,
                    )
            else:
                self.backend.conn.execute(
                    "INSERT INTO sources(source_id, source_type, uri, name, current_hash, status, created_at, updated_at) VALUES(?,?,?,?,?,'active',?,?)",
                    (source_id, source_type, uri, name or uri, content_hash, ts, ts),
                )
            episode_id = self._new_id("ep")
            self.backend.conn.execute(
                "INSERT INTO episodes(episode_id, source_id, episode_type, content_hash, raw_text, status, supersedes_episode_id, created_at) VALUES(?,?,?,?,?,'active',?,?)",
                (episode_id, source_id, episode_type, content_hash, content, supersedes_episode_id, ts),
            )
            chunk_count = 0
            for locator, text in self.chunk_content(content, source_type):
                chunk_id = self._new_id("chunk")
                self.backend.conn.execute(
                    "INSERT INTO chunks(chunk_id, episode_id, source_id, locator, text, content_hash, status, created_at) VALUES(?,?,?,?,?,?,'active',?)",
                    (chunk_id, episode_id, source_id, locator, text, self._sha256_text(text), ts),
                )
                self.backend._upsert_chunk_fts(chunk_id, source_id, locator, text)
                chunk_count += 1
            review_update = self.mark_claims_without_active_support(old_chunk_ids)
        chunk_refs = self.chunk_refs_for_source(source_id)
        recommended = self.recommend_evidence_candidates(
            source_id,
            evidence_hint=evidence_hint,
            claim_text=claim_text,
            evidence_lines=evidence_lines,
            limit=recommend_limit,
        )
        result = {
            "status": "ingested",
            "source_id": source_id,
            "episode_id": episode_id,
            "current_hash": content_hash,
            "chunks": chunk_count,
            "content_bytes": content_bytes,
            "chunk_ids": [c["chunk_id"] for c in chunk_refs],
            "chunk_refs": chunk_refs,
            "recommended_evidence_candidates": recommended,
            "recommendation_warning": self.evidence_recommendation_warning(recommended, evidence_hint, claim_text, evidence_lines),
            "evidence_note": "Use these exact chunk_ids for claim evidence; do not infer chunk IDs from source_id or episode_id.",
            "superseded_episode_id": supersedes_episode_id,
            "stale_chunk_ids": old_chunk_ids,
            "affected_claim_ids": review_update["affected_claim_ids"],
            "claims_marked_needs_review": review_update["claims_marked_needs_review"],
        }
        self.backend._log(
            "info",
            "ingest.done",
            source_id=source_id,
            episode_id=episode_id,
            uri=uri,
            content_bytes=content_bytes,
            chunks=chunk_count,
            stale_chunks=len(old_chunk_ids),
            affected_claims=len(review_update["affected_claim_ids"]),
            claims_marked_needs_review=len(review_update["claims_marked_needs_review"]),
            superseded_episode_id=supersedes_episode_id,
            elapsed_ms=(time.perf_counter() - started) * 1000,
        )
        return result

    def evidence_recommendation_warning(
        self,
        candidates: list[dict[str, Any]],
        evidence_hint: str | None,
        claim_text: str | None,
        evidence_lines: list[dict[str, int]] | None,
    ) -> str | None:
        if not (evidence_hint or claim_text or evidence_lines):
            return None
        if not candidates:
            return "No evidence candidates matched the supplied hint/claim/lines. Do not guess chunk IDs; inspect chunk_refs or ingest a focused report."
        return "Candidates are retrieval hints from this source only, not proof. Curator must attach only chunks that directly support the claim."

    def recommend_evidence_candidates(
        self,
        source_id: str,
        *,
        evidence_hint: str | None,
        claim_text: str | None,
        evidence_lines: list[dict[str, int]] | None,
        limit: int,
    ) -> list[dict[str, Any]]:
        if not (evidence_hint or claim_text or evidence_lines):
            return []
        limit = max(1, int(limit))
        query_text = " ".join(part for part in (claim_text or "", evidence_hint or "") if part.strip())
        query_terms = self.recommendation_terms(query_text)
        line_ranges = self.normalize_evidence_lines(evidence_lines)
        rows = self.backend.conn.execute(
            """
            SELECT chunk_id, episode_id, locator, text
            FROM chunks
            WHERE source_id=? AND status='active'
            ORDER BY rowid
            """,
            (source_id,),
        ).fetchall()
        scored: list[dict[str, Any]] = []
        for row in rows:
            locator = str(row["locator"])
            text = str(row["text"])
            chunk_range = self.locator_line_range(locator)
            overlap_lines = self.line_overlap_count(chunk_range, line_ranges)
            chunk_terms = self.recommendation_terms(text)
            matched_terms = sorted(query_terms.intersection(chunk_terms))
            lexical_score = float(len(matched_terms))
            if query_terms:
                lexical_score += sum(1.0 for term in matched_terms if len(term) >= 6)
            if overlap_lines <= 0 and lexical_score <= 0:
                continue
            score = overlap_lines * 1000.0 + lexical_score
            if overlap_lines > 0 and lexical_score > 0:
                match_type = "line_overlap+text_match"
            elif overlap_lines > 0:
                match_type = "line_overlap"
            else:
                match_type = "text_match"
            reason_parts = []
            if overlap_lines:
                reason_parts.append(f"overlaps requested evidence lines by {overlap_lines} line(s)")
            if matched_terms:
                reason_parts.append("matches terms: " + ", ".join(matched_terms[:8]))
            preview = " ".join(text.split())
            if len(preview) > 220:
                preview = preview[:217] + "..."
            scored.append(
                {
                    "chunk_id": row["chunk_id"],
                    "episode_id": row["episode_id"],
                    "locator": locator,
                    "match_type": match_type,
                    "score": round(score, 3),
                    "matched_terms": matched_terms[:12],
                    "preview": preview,
                    "reason": "; ".join(reason_parts),
                }
            )
        scored.sort(key=lambda item: (-float(item["score"]), str(item["locator"]), str(item["chunk_id"])))
        return scored[:limit]

    def recommendation_terms(self, text: str) -> set[str]:
        raw_terms = re.findall(r"[A-Za-z_][A-Za-z0-9_]*|[0-9]+", text)
        stop = {
            "and",
            "are",
            "but",
            "for",
            "from",
            "has",
            "have",
            "into",
            "not",
            "the",
            "this",
            "that",
            "with",
            "when",
        }
        return {term.lower() for term in raw_terms if len(term) >= 2 and term.lower() not in stop}

    def normalize_evidence_lines(self, evidence_lines: list[dict[str, int]] | None) -> list[tuple[int, int]]:
        ranges: list[tuple[int, int]] = []
        for item in evidence_lines or []:
            try:
                start = int(item.get("start", item.get("line", 0)))
                end = int(item.get("end", start))
            except Exception:
                continue
            if start <= 0 or end <= 0:
                continue
            if end < start:
                start, end = end, start
            ranges.append((start, end))
        return ranges

    def locator_line_range(self, locator: str) -> tuple[int, int] | None:
        m = re.search(r"lines\s+(\d+)-(\d+)", locator)
        if not m:
            return None
        return int(m.group(1)), int(m.group(2))

    def line_overlap_count(self, chunk_range: tuple[int, int] | None, requested_ranges: list[tuple[int, int]]) -> int:
        if not chunk_range or not requested_ranges:
            return 0
        start, end = chunk_range
        total = 0
        for req_start, req_end in requested_ranges:
            overlap_start = max(start, req_start)
            overlap_end = min(end, req_end)
            if overlap_start <= overlap_end:
                total += overlap_end - overlap_start + 1
        return total

    def chunk_refs_for_source(self, source_id: str, preview_chars: int = 180) -> list[dict[str, Any]]:
        rows = self.backend.conn.execute(
            """
            SELECT chunk_id, episode_id, locator, text, status
            FROM chunks
            WHERE source_id=? AND status='active'
            ORDER BY rowid
            """,
            (source_id,),
        ).fetchall()
        refs: list[dict[str, Any]] = []
        for row in rows:
            preview = " ".join(str(row["text"]).split())
            if len(preview) > preview_chars:
                preview = preview[: preview_chars - 3] + "..."
            refs.append(
                {
                    "chunk_id": row["chunk_id"],
                    "episode_id": row["episode_id"],
                    "locator": row["locator"],
                    "status": row["status"],
                    "preview": preview,
                }
            )
        return refs

    def mark_claims_without_active_support(self, affected_chunk_ids: list[str]) -> dict[str, list[str]]:
        if not affected_chunk_ids:
            return {"affected_claim_ids": [], "claims_marked_needs_review": []}
        marks = ",".join("?" for _ in affected_chunk_ids)
        affected_claims = [
            r["claim_id"]
            for r in self.backend.conn.execute(
                f"SELECT DISTINCT claim_id FROM claim_evidence WHERE chunk_id IN ({marks})",
                affected_chunk_ids,
            ).fetchall()
        ]
        marked_needs_review: list[str] = []
        for claim_id in affected_claims:
            active_support = self.backend.conn.execute(
                """
                SELECT 1
                FROM claim_evidence ce
                JOIN chunks ch ON ch.chunk_id = ce.chunk_id
                WHERE ce.claim_id=?
                  AND ce.evidence_role='supports'
                  AND ce.status='active'
                  AND ch.status='active'
                LIMIT 1
                """,
                (claim_id,),
            ).fetchone()
            if not active_support:
                cur = self.backend.conn.execute(
                    "UPDATE claims SET status='needs_review', updated_at=? WHERE claim_id=? AND status='active'",
                    (self._now_ts(), claim_id),
                )
                if cur.rowcount:
                    marked_needs_review.append(claim_id)
        return {
            "affected_claim_ids": affected_claims,
            "claims_marked_needs_review": marked_needs_review,
        }
